import os
import csv
import re
import numpy as np

import torch
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split

from config import Config


TF_METADATA_FILE_NAME = 'tf_per_file_metadata.csv'
TF_METADATA_FIELDS = [
    'sample_id',
    'subject_id',
    'num_epochs',
    'EEG Fpz-Cz TF path',
    'EEG Pz-Oz TF path',
    'EOG TF path',
    'label path',
]
SLEEP_EDF_SUBJECT_RE = re.compile(r'^[A-Za-z]{2}\d{4}')


def infer_subject_id_from_sample_id(sample_id):
    """Infer the expected Sleep-EDF subject id from a metadata sample id."""
    match = SLEEP_EDF_SUBJECT_RE.match(sample_id)
    if match:
        return match.group(0)
    return sample_id[:6] if len(sample_id) >= 6 else sample_id


def validate_metadata_path_sample_id(row_index, sample_id, relative_path, expected_suffix):
    """Ensure metadata path basename points to the same sample id."""
    basename = os.path.basename(relative_path)
    if not basename.endswith(expected_suffix):
        raise ValueError(
            f'[ERROR] Row {row_index} path has unexpected suffix for {sample_id}: {relative_path}'
        )

    path_sample_id = basename[:-len(expected_suffix)]
    if path_sample_id != sample_id:
        raise ValueError(
            f'[ERROR] Row {row_index} sample_id/path mismatch: '
            f'sample_id={sample_id}, path sample_id={path_sample_id}, path={relative_path}'
        )


def print_label_distribution(labels, split_name='labels'):
    """Print label distribution."""
    if isinstance(labels, torch.Tensor):
        labels_np = labels.cpu().numpy()
    else:
        labels_np = labels

    unique, counts = np.unique(labels_np, return_counts=True)
    total = len(labels_np)

    print(f'[{split_name}] label distribution:')
    for u, c in zip(unique, counts):
        print(f'  class {u}: {c} ({c / total:.6f})')


def load_per_file_tf_metadata(path_dataset):
    """Load and validate per-file TF metadata generated by preprocess_tf.py."""
    metadata_path = os.path.join(path_dataset, TF_METADATA_FILE_NAME)
    if not os.path.exists(metadata_path):
        raise FileNotFoundError(f'[ERROR] Missing per-file TF metadata: {metadata_path}')

    rows = []
    with open(metadata_path, newline='') as f:
        reader = csv.DictReader(f)
        missing_fields = sorted(set(TF_METADATA_FIELDS) - set(reader.fieldnames or []))
        if missing_fields:
            raise ValueError(f'[ERROR] Metadata file is missing fields: {missing_fields}')
        rows = list(reader)

    seen_sample_ids = set()
    for row_index, row in enumerate(rows):
        sample_id = row['sample_id'].strip()
        subject_id = row['subject_id'].strip()

        if not sample_id:
            raise ValueError(f'[ERROR] Row {row_index} has empty sample_id.')
        if sample_id in seen_sample_ids:
            raise ValueError(f'[ERROR] Duplicate sample_id in metadata: {sample_id}')
        seen_sample_ids.add(sample_id)

        if not subject_id:
            raise ValueError(f'[ERROR] Row {row_index} sample_id={sample_id} has empty subject_id.')

        expected_subject_id = infer_subject_id_from_sample_id(sample_id)
        if subject_id != expected_subject_id:
            raise ValueError(
                f'[ERROR] Row {row_index} subject_id mismatch for {sample_id}: '
                f'expected {expected_subject_id}, got {subject_id}'
            )

        row['sample_id'] = sample_id
        row['subject_id'] = subject_id
        try:
            num_epochs = int(row['num_epochs'])
        except ValueError as exc:
            raise ValueError(f'[ERROR] Invalid num_epochs for row {row_index}: {row["num_epochs"]!r}') from exc

        tf_paths = [
            row['EEG Fpz-Cz TF path'].strip(),
            row['EEG Pz-Oz TF path'].strip(),
            row['EOG TF path'].strip(),
        ]
        label_path = row['label path'].strip()

        validate_metadata_path_sample_id(row_index, sample_id, tf_paths[0], '_TF_EEG_Fpz-Cz_mean_std.npy')
        validate_metadata_path_sample_id(row_index, sample_id, tf_paths[1], '_TF_EEG_Pz-Oz_mean_std.npy')
        validate_metadata_path_sample_id(row_index, sample_id, tf_paths[2], '_TF_EOG_mean_std.npy')
        validate_metadata_path_sample_id(row_index, sample_id, label_path, '_label.npy')

        for relative_path in tf_paths + [label_path]:
            full_path = os.path.join(path_dataset, relative_path)
            if not os.path.exists(full_path):
                raise FileNotFoundError(f'[ERROR] Metadata path does not exist for {sample_id}: {full_path}')

        channel_shapes = [
            np.load(os.path.join(path_dataset, relative_path), mmap_mode='r').shape
            for relative_path in tf_paths
        ]
        label_shape = np.load(os.path.join(path_dataset, label_path), mmap_mode='r').shape

        expected_tf_shape = (num_epochs, 29, 128)
        if any(shape != expected_tf_shape for shape in channel_shapes):
            raise ValueError(
                f'[ERROR] {sample_id} channel shape mismatch: '
                f'expected {expected_tf_shape}, got {channel_shapes}'
            )
        if label_shape != (num_epochs,):
            raise ValueError(
                f'[ERROR] {sample_id} label shape mismatch: '
                f'expected ({num_epochs},), got {label_shape}'
            )

        row['num_epochs'] = num_epochs
        row['EEG Fpz-Cz TF path'] = tf_paths[0]
        row['EEG Pz-Oz TF path'] = tf_paths[1]
        row['EOG TF path'] = tf_paths[2]
        row['label path'] = label_path

    print(f'[INFO] Loaded {len(rows)} per-file TF metadata rows from {metadata_path}')
    return rows


def data_generator(path_labels, path_dataset):
    config = Config()

    # 1. 一定要排序，保证和 preprocess_tf.py 的拼接顺序一致
    label_files = sorted([f for f in os.listdir(path_labels) if f.endswith('.npy')])

    print('[INFO] label files (first 10):')
    for f in label_files[:10]:
        print(f'  {f}')

    # 2. 按排序后的文件顺序拼接 labels
    label_list = []
    for f in label_files:
        y = np.load(os.path.join(path_labels, f))
        label_list.append(y)

    labels = np.concatenate(label_list, axis=0).astype(np.int64)
    labels = torch.from_numpy(labels)

    # 3. 读取三个通道的 TF 数据
    dataset_EEG_FpzCz = np.load(
        os.path.join(path_dataset, 'TF_EEG_Fpz-Cz_mean_std.npy')
    ).astype('float32')

    dataset_EEG_PzOz = np.load(
        os.path.join(path_dataset, 'TF_EEG_Pz-Oz_mean_std.npy')
    ).astype('float32')

    dataset_EOG = np.load(
        os.path.join(path_dataset, 'TF_EOG_mean_std.npy')
    ).astype('float32')

    # 4. 堆叠成 [N, 3, 29, 128]
    dataset = np.stack((dataset_EEG_FpzCz, dataset_EEG_PzOz, dataset_EOG), axis=1)
    dataset = torch.from_numpy(dataset)

    print(f'[INFO] dataset shape: {dataset.shape}')
    print(f'[INFO] labels shape: {labels.shape}')

    # 5. 安全检查：样本数必须一致
    if len(dataset) != len(labels):
        raise ValueError(
            f'[ERROR] dataset size ({len(dataset)}) != labels size ({len(labels)})'
        )

    print_label_distribution(labels, split_name='full dataset')

    # 6. 固定留出验证集
    X_train_test, X_val, y_train_test, y_val = train_test_split(
        dataset,
        labels,
        # This test_size is the held-out validation ratio, not the K-fold test ratio.
        test_size=config.val_ratio,
        random_state=0,
        stratify=labels
    )

    print(f'[INFO] train_test size: {len(X_train_test)}')
    print(f'[INFO] val size: {len(X_val)}')

    print_label_distribution(y_train_test, split_name='train_test')
    print_label_distribution(y_val, split_name='val')

    val_set = TensorDataset(X_val, y_val)
    val_loader = DataLoader(
        dataset=val_set,
        batch_size=config.batch_size,
        shuffle=False,
        num_workers=12,
        pin_memory=True,
        persistent_workers=True,
        prefetch_factor=2
    )

    return X_train_test, y_train_test, val_loader


if __name__ == '__main__':
    # 方便单独测试
    from config import Path

    path = Path()
    data_generator(path_labels=path.path_labels, path_dataset=path.path_TF)



'''
import os
import numpy as np

import torch
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split

from config import Config, Path


def data_generator(path_labels, path_dataset):
    config = Config()
    dir_annotation = os.listdir(path_labels)

    first = True
    for f in dir_annotation:
        if first:
            labels = np.load(os.path.join(path_labels, f))
            first = False
        else:
            temp = np.load(os.path.join(path_labels, f))
            labels = np.append(labels, temp, axis=0)
    labels = torch.from_numpy(labels)

    dataset_EEG_FpzCz = np.load(os.path.join(path_dataset, 'TF_EEG_Fpz-Cz_mean_std.npy')).astype('float32')
    dataset_EEG_PzOz = np.load(os.path.join(path_dataset, 'TF_EEG_Pz-Oz_mean_std.npy')).astype('float32')
    dataset_EOG = np.load(os.path.join(path_dataset, 'TF_EOG_mean_std.npy')).astype('float32')

    dataset = np.stack((dataset_EEG_FpzCz, dataset_EEG_PzOz, dataset_EOG), axis=1)
    dataset = torch.from_numpy(dataset)

    print('dataset: ', dataset.shape)

    # hold out the validation set
    X_train_test, X_val, y_train_test, y_val = train_test_split(dataset, labels, test_size=1/(config.num_fold+1), random_state=0, stratify=labels)

    val_set = TensorDataset(X_val, y_val)
    #val_loader = DataLoader(dataset=val_set, batch_size=config.batch_size, shuffle=False)
    val_loader = DataLoader(
        dataset=val_set,
        batch_size=config.batch_size,
        shuffle=False,
        num_workers=8,
        pin_memory=True,
        persistent_workers=True,
        prefetch_factor=2
    )

    print('val_set:', len(X_val))
    return X_train_test, y_train_test, val_loader
'''
